'use client';

/**
 * CMR Creation Wizard - 3-Step Form
 *
 * This wizard guides drivers/dispatchers through creating a new CMR document.
 *
 * FRESH FORM ON MOUNT:
 * - The form is ALWAYS reset to clean defaults when this page loads.
 * - No stale values from previous CMR creations are retained.
 * - Only defaults from profile/vehicles data and hard-coded values are used.
 * - Draft auto-save is disabled to prevent stale data from leaking between sessions.
 *
 * AUTOFILL STRATEGY - Minimize Redundant Data Entry:
 * - We try to minimize manual input by reusing profile + vehicles data
 * - Driver mainly enters mission-specific data (shipper/consignee/goods/instructions)
 * - Transporter info is NEVER duplicated in cmr_documents - it lives in profiles table
 * - When generating PDFs or displaying CMR, we fetch transporter info from profiles
 *
 * AUTOFILL SOURCES:
 * - profiles table: Company name, address, SIREN/SIRET, phone (used for "Transporteur" on CMR)
 * - vehicles table: Auto-select first vehicle (or last used vehicle)
 * - Sensible defaults: freight_currency='EUR', flags=false, loading_date=today
 *
 * CMR NUMBER GENERATION:
 * - CMR number is NOT editable by the user in this form.
 * - It is auto-generated by the database on insert (using sequence or trigger).
 * - The generated number is displayed on the CMR details page (/cmr/[id]) and in PDFs.
 *
 * STEP 1 - BASE INFORMATION:
 * - Parties (shipper, consignee, optional principal/delivery carrier)
 * - Addresses (with autocomplete)
 * - Basic planning (loading date, requested delivery)
 * - International flag
 *
 * STEP 2 - GOODS & CONDITIONS:
 * - Goods description, packages, weight
 * - Packaging and marks
 * - Dangerous goods (ADR) - conditionally shown
 * - Temperature control - conditionally shown
 * - Financial info (COD, freight)
 * - Pallets management
 * - Instructions and documents
 *
 * STEP 3 - VEHICLE & SUMMARY:
 * - Vehicle selection from user's fleet
 * - Read-only summary of all entered data
 * - Final submission
 *
 * LIFECYCLE HANDLED HERE:
 * - CMR creation with status = 'ready_to_load'
 * - All optional fields can be left empty and filled later
 *
 * NOT HANDLED HERE (managed elsewhere):
 * - Loading/Delivery reserves (added during transport)
 * - Photos (added during loading/delivery)
 * - Signatures (added at loading/delivery)
 * - Status transitions (managed by workflow components)
 */

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { format } from 'date-fns';

import type { Resolver, SubmitHandler, } from 'react-hook-form';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Calendar } from '@/components/ui/calendar';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import { Stepper } from '@/components/ui/stepper';
// Client-side Supabase instance used for CMR insert from the /cmr/new page
import { supabase } from '@/lib/supabaseClient';
import { cmrSchema, type CmrInput } from '@/lib/validations/cmr.schema';
import { useAuthStore } from '@/store/auth.store';
import {
  ArrowLeft,
  ArrowRight,
  Check,
  Calendar as CalendarIcon,
  AlertTriangle,
  Thermometer,
  Package,
  FileText,
  Euro,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { AddressAutocomplete } from '@/components/forms/AddressAutocomplete';
import type { Database } from '@/types/database.types';

type Vehicle = Database['public']['Tables']['vehicles']['Row'];
type Profile = Database['public']['Tables']['profiles']['Row'];

/**
 * Wizard steps configuration
 * Each step has a title and description for the stepper UI
 */
const STEPS = [
  { title: 'Parties & Planning', description: 'Who, where, when' },
  { title: 'Goods & Conditions', description: 'What and how' },
  { title: 'Vehicle & Summary', description: 'Review and create' },
];

export function CmrFormWizard() {
  const router = useRouter();
  const { user } = useAuthStore();

  // UI State
  const [currentStep, setCurrentStep] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  // Data from backend
  const [_profile, setProfile] = useState<Profile | null>(null);
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [loadingVehicles, setLoadingVehicles] = useState(true);

  /**
   * React Hook Form setup with updated schema
   * Single form instance used across all 3 steps
   *
   * FRESH FORM DEFAULTS:
   * These defaults are ONLY applied on first render, then overridden by the
   * useEffect below that resets the form with fresh data from profile/vehicles.
   *
   * Default Values:
   * - loading_date: Today's date (driver rarely creates CMR for past dates)
   * - is_international: false (most transport is domestic, can be toggled if needed)
   * - is_dangerous_goods: false (most cargo is not ADR, can be toggled if needed)
   * - is_controlled_temperature: false (most cargo is not refrigerated, can be toggled)
   * - freight_currency: 'EUR' (default currency for freight charges)
   * - vehicle_id: Will be auto-selected to first vehicle in useEffect below
   */
const {
  register,
  handleSubmit,
  watch,
  reset,
  control,
  formState,
  trigger,
} = useForm<CmrInput>({
  resolver: zodResolver(cmrSchema) as Resolver<CmrInput>,
  mode: 'onSubmit',
  defaultValues: {
    loading_date: new Date().toISOString().split('T')[0],
    is_international: false,
    is_dangerous_goods: false,
    is_controlled_temperature: false,
    freight_currency: 'EUR',
  },
});
  // Extract errors and isSubmitting from formState
  const { errors, isSubmitting } = formState;

  // TODO: remove debug log once submit flow is stable
  console.log('[CMR Form] Component rendered');

  // Watch all form values for summary display in Step 3
  const formValues = watch();

  // Watch conditional fields to show/hide sections dynamically
  const isDangerousGoods = watch('is_dangerous_goods');
  const isControlledTemp = watch('is_controlled_temperature');
  const isInternational = watch('is_international');

  /**
   * AUTOFILL - Load user profile on mount
   *
   * Profile data is used for:
   * - Displaying transporter info (company name, address, SIREN/SIRET) on CMR details page
   * - PDF generation (transporter block on official CMR document)
   *
   * NOTE: We do NOT duplicate transporter info into cmr_documents table.
   * The transporter is always the authenticated user's company (from profiles).
   * This avoids redundancy and ensures consistency across all CMRs.
   */
  useEffect(() => {
    const loadProfile = async () => {
      if (!user) return;

      try {
        const { data, error } = await supabase
          .from('profiles')
          .select('*')
          .eq('id', user.id)
          .maybeSingle();

        if (error) {
          console.error('Error loading profile:', error);
          return;
        }

        if (data) {
          setProfile(data);
        }
      } catch (err) {
        console.error('Unexpected error loading profile:', err);
      }
    };

    loadProfile();
  }, [user]);

  /**
   * AUTOFILL - Load vehicles from user's fleet on mount
   *
   * Vehicle selection is required in Step 3.
   * Auto-selects the first vehicle (most recently created) if available.
   *
   * FUTURE: Could store "last used vehicle ID" in localStorage or Zustand
   * to remember user's preferred vehicle across CMR creations.
   */
  useEffect(() => {
    const loadVehicles = async () => {
      if (!user) return;

      try {
        const { data, error } = await supabase
          .from('vehicles')
          .select('*')
          .eq('user_id', user.id)
          .order('created_at', { ascending: false });

        if (error) throw error;

        setVehicles(data || []);
      } catch (err) {
        console.error('Error loading vehicles:', err);
      } finally {
        setLoadingVehicles(false);
      }
    };

    loadVehicles();
  }, [user]);

  /**
   * FRESH FORM RESET - Ensure clean form on mount
   *
   * This effect runs after profile and vehicles are loaded.
   * It resets the form to FRESH defaults derived from:
   * - Hard-coded defaults (loading_date = today, flags = false, currency = EUR)
   * - First available vehicle from user's fleet
   *
   * IMPORTANT: We do NOT load drafts to prevent stale data from previous CMR
   * creations. Each "New CMR" session starts completely fresh.
   *
   * The form will be reset when:
   * 1. Component mounts (initial load)
   * 2. User data is ready
   * 3. Vehicles list has been loaded
   */
  useEffect(() => {
    // Only reset once we have all the data we need
    if (!user || loadingVehicles) return;

    // Compute fresh default values
    const freshDefaults: Partial<CmrInput> = {
      loading_date: new Date().toISOString().split('T')[0],
      is_international: false,
      is_dangerous_goods: false,
      is_controlled_temperature: false,
      freight_currency: 'EUR',
      // Auto-select first vehicle if available
      vehicle_id: vehicles.length > 0 ? vehicles[0].id : undefined,
    };

    // Reset form to fresh defaults
    reset(freshDefaults);
    console.log('[CMR Form] Form reset to fresh defaults');
  }, [user, vehicles, loadingVehicles, reset]);

  /**
   * DEBUG - Log form state changes
   * TODO: remove this useEffect once submit flow is stable
   */
  useEffect(() => {
    console.log('[CMR Form] Form state changed:', {
      isValid: formState.isValid,
      isSubmitting: formState.isSubmitting,
      errors: formState.errors,
      isDirty: formState.isDirty,
    });
  }, [formState]);

  /**
   * Navigate to next step
   * Could add per-step validation here if needed
   */
const handleNext = async () => {
  let fieldsToValidate: (keyof CmrInput)[] = [];

  if (currentStep === 0) {
    // Champs obligatoires du step 1
    fieldsToValidate = [
      'shipper_name',
      'shipper_address',
      'consignee_name',
      'consignee_address',
      'loading_place',
      'delivery_place',
      'loading_date',
    ];
  } else if (currentStep === 1) {
    // Champs obligatoires du step 2
    fieldsToValidate = [
      'goods_description',
      'packages_count',
      'weight_kg',
      // tu peux en rajouter si tu veux les rendre “bloquants” pour passer à l'étape 3
    ];
  }

  // Si tu ne veux aucune validation sur certains steps, tu peux laisser le tableau vide

  if (fieldsToValidate.length > 0) {
    const isStepValid = await trigger(fieldsToValidate);
    if (!isStepValid) {
      // On reste sur le step courant, erreurs visibles
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }
  }

  // OK → on passe au step suivant
  if (currentStep < STEPS.length - 1) {
    setCurrentStep((prev) => prev + 1);
    setError(null);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
};

  /**
   * Navigate to previous step
   */
  const handleBack = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
      setError(null);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  /**
   * Final form submission - CREATE CMR
   *
   * This is the ONLY handler that creates CMR documents in the database.
   *
   * FLOW:
   * 1. Validate all form data using Zod schema (handled by React Hook Form)
   * 2. Map form values to database insert payload
   * 3. Insert new CMR document with status = 'ready_to_load'
   * 4. On success: Redirect to /cmr/[id] to view the created CMR
   * 5. On error: Display error message to user for debugging
   *
   * CMR NUMBER GENERATION:
   * - We do NOT allow user to edit cmr_number in the form.
   * - The database auto-generates it (via sequence, trigger, or default value).
   * - The generated number is visible on /cmr/[id] page and in PDFs.
   *
   * TRANSPORTER INFO NOT STORED:
   * - Transporter/carrier info (company name, address, SIREN, phone) is NOT stored in cmr_documents.
   * - It lives in the profiles table and is fetched when displaying CMR or generating PDFs.
   * - This ensures a single source of truth and consistency across all documents.
   *
   * ERROR HANDLING:
   * - All Supabase errors are logged to console for debugging.
   * - User-visible error messages are displayed in the UI via the 'error' state.
   */
const onSubmit: SubmitHandler<CmrInput> = async (data) => {
    // TODO: remove debug logs once submit flow is stable
    console.log('[CMR Submit] onSubmit called with data:', data);
    console.log('[CMR Submit] Form state:', { isSubmitting, loading, user: !!user, vehicles: vehicles.length });

    if (!user) {
      console.error('[CMR Submit] No user found');
      setError('You must be logged in to create a CMR');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      // Construct insert object with all fields from the schema
      // Only include fields that have values (Supabase will use defaults/nulls for rest)
      //
      // NOTE: Transporter info is NOT included here - it comes from profiles table
      const insertData: Database['public']['Tables']['cmr_documents']['Insert'] = {
        // System fields
        user_id: user.id,
        status: 'ready_to_load',

        // Basic CMR info
        // NOTE: cmr_number is auto-generated by database, not provided by user
        cmr_number: null,
        is_international: data.is_international || false,

        // Parties (shipper, consignee, optional principal/delivery carrier)
        // NOTE: Transporter is NOT stored here - comes from profiles table
        shipper_name: data.shipper_name,
        shipper_address: data.shipper_address || null,
        consignee_name: data.consignee_name,
        consignee_address: data.consignee_address || null,
        principal_name: data.principal_name || null,
        principal_address: data.principal_address || null,
        delivery_carrier_name: data.delivery_carrier_name || null,
        delivery_carrier_address: data.delivery_carrier_address || null,

        // Goods
        goods_description: data.goods_description || null,
        packages_count: data.packages_count || null,
        weight_kg: data.weight_kg || null,
        packaging_type: data.packaging_type || null,
        goods_marks_numbers: data.goods_marks_numbers || null,
        declared_value: data.declared_value || null,
        declared_value_currency: data.declared_value_currency || null,

        // Locations & timing
        loading_place: data.loading_place,
        delivery_place: data.delivery_place,
        loading_date: data.loading_date,
        requested_delivery_at: data.requested_delivery_at || null,
        loading_arrival_at: data.loading_arrival_at || null,
        loading_departure_at: data.loading_departure_at || null,
        delivery_arrival_at: data.delivery_arrival_at || null,
        delivery_departure_at: data.delivery_departure_at || null,

        // Extra services
        loading_extra_services: data.loading_extra_services || null,
        delivery_extra_services: data.delivery_extra_services || null,

        // Dangerous goods
        is_dangerous_goods: data.is_dangerous_goods || false,
        dangerous_goods_class: data.dangerous_goods_class || null,
        dangerous_goods_un_number: data.dangerous_goods_un_number || null,
        dangerous_goods_adr_letter: data.dangerous_goods_adr_letter || null,

        // Temperature
        is_controlled_temperature: data.is_controlled_temperature || false,
        temperature_min: data.temperature_min || null,
        temperature_max: data.temperature_max || null,

        // Financial
        cash_on_delivery_amount: data.cash_on_delivery_amount || null,
        cash_on_delivery_currency: data.cash_on_delivery_currency || null,
        freight_total_amount: data.freight_total_amount || null,
        freight_currency: data.freight_currency || 'EUR',
        freight_terms: data.freight_terms || null,

        // Pallets
        pallets_80_120: data.pallets_80_120 || null,
        pallets_100_120: data.pallets_100_120 || null,
        pallets_europe: data.pallets_europe || null,
        pallets_others: data.pallets_others || null,
        pallets_bacs: data.pallets_bacs || null,
        pallets_rolls: data.pallets_rolls || null,
        pallets_origin: data.pallets_origin || null,
        pallets_loaded_at_shipper: data.pallets_loaded_at_shipper || null,
        pallets_returned_to_shipper: data.pallets_returned_to_shipper || null,
        pallets_delivered_to_consignee: data.pallets_delivered_to_consignee || null,
        pallets_returned_by_consignee: data.pallets_returned_by_consignee || null,
        pallets_deposited_at: data.pallets_deposited_at || null,
        pallets_final_balance: data.pallets_final_balance || null,

        // Instructions & documents
        instructions: data.instructions || null,
        customs_instructions: data.customs_instructions || null,
        attached_documents: data.attached_documents || null,

        // Vehicle
        vehicle_id: data.vehicle_id,
      };

      // TODO: remove debug log once submit flow is stable
      console.log('[CMR Submit] Inserting into Supabase with payload:', insertData);

      const { data: cmrData, error: insertError } = await supabase
        .from('cmr_documents')
        .insert(insertData)
        .select()
        .single();

      // TODO: remove debug log once submit flow is stable
      console.log('[CMR Submit] Supabase response:', { data: cmrData, error: insertError });

      if (insertError) {
        console.error('[CMR Submit] Supabase insert error:', insertError);
        setError(`Failed to create CMR: ${insertError.message}`);
        return;
      }

      if (!cmrData) {
        console.error('[CMR Submit] No data returned from Supabase');
        setError('Failed to create CMR: No data returned from database');
        return;
      }

      // TODO: remove debug log once submit flow is stable
      console.log('[CMR Submit] CMR created successfully, redirecting to:', `/cmr/${cmrData.id}`);

      // Redirect to the new CMR detail page
      router.push(`/cmr/${cmrData.id}`);
    } catch (err) {
      console.error('[CMR Submit] Unexpected error during submission:', err);
      setError(`An unexpected error occurred: ${err instanceof Error ? err.message : 'Unknown error'}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Stepper */}
      <Stepper steps={STEPS} currentStep={currentStep} />

      {/* Error Alert */}
      {error && (
        <div className="rounded-md bg-red-50 border border-red-200 p-4 text-sm text-red-800">
          <p className="font-medium">Error</p>
          <p>{error}</p>
        </div>
      )}

      {/* Form

          DRIVER-FRIENDLY FIELD DESCRIPTIONS:
          Specific fields include helper text (FormDescription) to guide drivers who may not
          be familiar with technical terms (ADR, COD, etc.) or industry-specific requirements.
          This reduces errors and support calls by clarifying what information is needed and where
          to find it (client documents, product specs, etc.).
      */}
      <form  onSubmit={(e) => {
                e.preventDefault(); // le form ne soumet plus rien tout seul
                  }}
                 className="space-y-6">
        {/* ====================================================================
            STEP 1 - BASE INFORMATION
            Parties, addresses, basic planning
            ==================================================================== */}
        {currentStep === 0 && (
          <div className="space-y-6">
            {/* International Transport Toggle */}
            <Card>
              <CardHeader>
                <CardTitle>Transport Type</CardTitle>
                <CardDescription>Specify if this transport crosses international borders</CardDescription>
              </CardHeader>
              <CardContent>
                {/* International toggle */}
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label htmlFor="is_international">International Transport</Label>
                    <p className="text-sm text-muted-foreground">
                      Enable if transport crosses international borders
                    </p>
                  </div>
                  <Controller
                    name="is_international"
                    control={control}
                    render={({ field }) => (
                      <Switch
                        id="is_international"
                        checked={field.value}
                        onCheckedChange={field.onChange}
                      />
                    )}
                  />
                </div>
              </CardContent>
            </Card>

            {/* Shipper (required) */}
            <Card>
              <CardHeader>
                <CardTitle>Shipper (Expéditeur)</CardTitle>
                <CardDescription>Who is sending the goods</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  {/* We use a single neutral asterisk to indicate required fields, avoiding color noise for drivers */}
                  <Label htmlFor="shipper_name">Company Name*</Label>
                  <Input
                    id="shipper_name"
                    {...register('shipper_name')}
                    placeholder="ABC Logistics"
                  />
                  {errors.shipper_name && (
                    <p className="text-sm text-destructive">{errors.shipper_name.message}</p>
                  )}
                </div>

                <Controller
                  name="shipper_address"
                  control={control}
                  render={({ field }) => (
                    <AddressAutocomplete
                      label="Address*"
                      placeholder="Start typing address..."
                      value={field.value || ''}
                      onChange={field.onChange}
                      
                      error={errors.shipper_address?.message}
                    />
                  )}
                />
              </CardContent>
            </Card>

            {/* Consignee (required) */}
            <Card>
              <CardHeader>
                <CardTitle>Consignee (Destinataire)</CardTitle>
                <CardDescription>Who is receiving the goods</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="consignee_name">Company name*</Label>
                  <Input
                    id="consignee_name"
                    {...register('consignee_name')}
                    placeholder="XYZ Warehouse"
                  />
                  {errors.consignee_name && (
                    <p className="text-sm text-destructive">{errors.consignee_name.message}</p>
                  )}
                </div>

                <Controller
                  name="consignee_address"
                  control={control}
                  render={({ field }) => (
                    <AddressAutocomplete
                      label="Address*"
                      placeholder="Start typing address..."
                      value={field.value || ''}
                      onChange={field.onChange}
                      error={errors.consignee_address?.message}
                    />
                  )}
                />
              </CardContent>
            </Card>

            {/* Optional: Principal & Delivery Carrier */}
            <Card>
              <CardHeader>
                <CardTitle>Additional Parties (Optional)</CardTitle>
                <CardDescription>
                  Principal (ordering party) and delivery carrier if different
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <Separator />
                <div className="space-y-4">
                  <h4 className="text-sm font-medium">Principal (Donneur d&apos;ordre)</h4>
                  <div className="space-y-2">
                    <Label htmlFor="principal_name">Name</Label>
                    <Input
                      id="principal_name"
                      {...register('principal_name')}
                      placeholder="Company ordering the transport"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="principal_address">Address</Label>
                    <Input
                      id="principal_address"
                      {...register('principal_address')}
                      placeholder="Principal address"
                    />
                  </div>
                </div>

                <Separator />
                <div className="space-y-4">
                  <h4 className="text-sm font-medium">Delivery Carrier (Transporteur successif)</h4>
                  <div className="space-y-2">
                    <Label htmlFor="delivery_carrier_name">Name</Label>
                    <Input
                      id="delivery_carrier_name"
                      {...register('delivery_carrier_name')}
                      placeholder="Successive carrier if applicable"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="delivery_carrier_address">Address</Label>
                    <Input
                      id="delivery_carrier_address"
                      {...register('delivery_carrier_address')}
                      placeholder="Carrier address"
                    />
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Transport Route & Timing */}
            <Card>
              <CardHeader>
                <CardTitle>Route & Planning</CardTitle>
                <CardDescription>Loading and delivery locations and times</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <Controller
                  name="loading_place"
                  control={control}
                  render={({ field }) => (
                    <AddressAutocomplete
                      label="Loading Place*"
                      placeholder="Where goods will be loaded..."
                      value={field.value || ''}
                      onChange={field.onChange}
                      error={errors.loading_place?.message}
                    />
                  )}
                />

                <Controller
                  name="delivery_place"
                  control={control}
                  render={({ field }) => (
                    <AddressAutocomplete
                      label="Delivery Place*"
                      placeholder="Where goods will be delivered..."
                      value={field.value || ''}
                      onChange={field.onChange}
                      error={errors.delivery_place?.message}
                    />
                  )}
                />

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {/* Loading Date (required) */}
                  <div className="space-y-2">
                    <Label htmlFor="loading_date">Loading Date*</Label>
                    <Controller
                      name="loading_date"
                      control={control}
                      render={({ field }) => (
                        <Popover>
                          <PopoverTrigger asChild>
                            <Button
                              variant="outline"
                              className={cn(
                                'w-full justify-start text-left font-normal',
                                !field.value && 'text-muted-foreground'
                              )}
                            >
                              <CalendarIcon className="mr-2 h-4 w-4" />
                              {field.value ? (
                                format(new Date(field.value), 'PPP')
                              ) : (
                                <span>Pick a date</span>
                              )}
                            </Button>
                          </PopoverTrigger>
                          <PopoverContent className="w-auto p-0">
                            <Calendar
                              mode="single"
                              selected={field.value ? new Date(field.value) : undefined}
                              onSelect={(date) => {
                                if (date) {
                                  field.onChange(format(date, 'yyyy-MM-dd'));
                                }
                              }}
                            />
                          </PopoverContent>
                        </Popover>
                      )}
                    />
                    {errors.loading_date && (
                      <p className="text-sm text-destructive">{errors.loading_date.message}</p>
                    )}
                  </div>

                  {/* Requested Delivery (optional) - DatePicker for mobile-friendly input */}
                  <div className="space-y-2">
                    <Label htmlFor="requested_delivery_at">Requested Delivery Date</Label>
                    <Controller
                      name="requested_delivery_at"
                      control={control}
                      render={({ field }) => (
                        <Popover>
                          <PopoverTrigger asChild>
                            <Button
                              variant="outline"
                              className={cn(
                                'w-full justify-start text-left font-normal',
                                !field.value && 'text-muted-foreground'
                              )}
                            >
                              <CalendarIcon className="mr-2 h-4 w-4" />
                              {field.value ? (
                                format(new Date(field.value), 'PPP')
                              ) : (
                                <span>Pick a date</span>
                              )}
                            </Button>
                          </PopoverTrigger>
                          <PopoverContent className="w-auto p-0">
                            <Calendar
                              mode="single"
                              selected={field.value ? new Date(field.value) : undefined}
                              onSelect={(date) => {
                                if (date) {
                                  field.onChange(format(date, 'yyyy-MM-dd'));
                                }
                              }}
                            />
                          </PopoverContent>
                        </Popover>
                      )}
                    />
                    <p className="text-xs text-muted-foreground">
                      Target delivery date requested by the client (optional, for planning and customer communication)
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* ====================================================================
            STEP 2 - GOODS & CONDITIONS
            Goods details, ADR, temperature, financial, pallets, instructions
            ==================================================================== */}
        {currentStep === 1 && (
          <div className="space-y-6">
            {/* Basic Goods Information */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Package className="h-5 w-5" />
                  Goods Information
                </CardTitle>
                <CardDescription>Description and quantities</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="goods_description">Description *</Label>
                  <Textarea
                    id="goods_description"
                    {...register('goods_description')}
                    placeholder="Electronics - Laptops and accessories"
                    rows={3}
                  />
                  {errors.goods_description && (
                    <p className="text-sm text-destructive">{errors.goods_description.message}</p>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="packages_count">Packages *</Label>
                    <Input
                      id="packages_count"
                      type="number"
                      min="1"
                      {...register('packages_count', { valueAsNumber: true })}
                      placeholder="50"
                    />
                    {errors.packages_count && (
                      <p className="text-sm text-destructive">{errors.packages_count.message}</p>
                    )}
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="weight_kg">Weight (kg) *</Label>
                    <Input
                      id="weight_kg"
                      type="number"
                      step="0.1"
                      min="0.1"
                      {...register('weight_kg', { valueAsNumber: true })}
                      placeholder="1200.5"
                    />
                    {errors.weight_kg && (
                      <p className="text-sm text-destructive">{errors.weight_kg.message}</p>
                    )}
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="packaging_type">Packaging Type</Label>
                  <Input
                    id="packaging_type"
                    {...register('packaging_type')}
                    placeholder="Pallets, boxes, bulk, etc."
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="goods_marks_numbers">Marks & Numbers</Label>
                  <Input
                    id="goods_marks_numbers"
                    {...register('goods_marks_numbers')}
                    placeholder="Identification marks on packages"
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="declared_value">Declared Value</Label>
                    <Input
                      id="declared_value"
                      type="number"
                      step="0.01"
                      {...register('declared_value')}
                      placeholder="10000"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="declared_value_currency">Currency</Label>
                    <Input
                      id="declared_value_currency"
                      {...register('declared_value_currency')}
                      placeholder="EUR"
                      maxLength={3}
                    />
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Dangerous Goods (ADR) */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <AlertTriangle className="h-5 w-5 text-orange-500" />
                  Dangerous Goods (ADR)
                </CardTitle>
                <CardDescription>For hazardous materials requiring ADR compliance</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label htmlFor="is_dangerous_goods">Contains Dangerous Goods</Label>
                    <p className="text-sm text-muted-foreground">
                      Requires ADR documentation and compliance
                    </p>
                  </div>
                  <Controller
                    name="is_dangerous_goods"
                    control={control}
                    render={({ field }) => (
                      <Switch
                        id="is_dangerous_goods"
                        checked={field.value}
                        onCheckedChange={field.onChange}
                      />
                    )}
                  />
                </div>

                {/* Description: Help drivers understand ADR fields - copy from client documents */}
                {isDangerousGoods && (
                  <div className="space-y-4 pt-4 border-t">
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="dangerous_goods_class">ADR Class</Label>
                        <Input
                          id="dangerous_goods_class"
                          {...register('dangerous_goods_class')}
                          placeholder="e.g., 3, 9"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="dangerous_goods_un_number">UN Number</Label>
                        <Input
                          id="dangerous_goods_un_number"
                          {...register('dangerous_goods_un_number')}
                          placeholder="e.g., UN1203"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="dangerous_goods_adr_letter">ADR Letter</Label>
                        <Input
                          id="dangerous_goods_adr_letter"
                          {...register('dangerous_goods_adr_letter')}
                          placeholder="e.g., F"
                        />
                      </div>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Copy these values from the client&apos;s ADR transport document or shipping papers. Only fill if transporting hazardous materials requiring ADR certification.
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Temperature Control */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Thermometer className="h-5 w-5 text-blue-500" />
                  Temperature Control
                </CardTitle>
                <CardDescription>For refrigerated or frozen transport</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label htmlFor="is_controlled_temperature">Controlled Temperature</Label>
                    <p className="text-sm text-muted-foreground">
                      Transport requires temperature monitoring
                    </p>
                  </div>
                  <Controller
                    name="is_controlled_temperature"
                    control={control}
                    render={({ field }) => (
                      <Switch
                        id="is_controlled_temperature"
                        checked={field.value}
                        onCheckedChange={field.onChange}
                      />
                    )}
                  />
                </div>

                {/* Description: Help drivers understand temperature requirements - check client specs */}
                {isControlledTemp && (
                  <div className="space-y-4 pt-4 border-t">
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="temperature_min">Min Temp (°C)</Label>
                        <Input
                          id="temperature_min"
                          type="number"
                          step="0.1"
                          {...register('temperature_min', { valueAsNumber: true })}
                          placeholder="-18"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="temperature_max">Max Temp (°C)</Label>
                        <Input
                          id="temperature_max"
                          type="number"
                          step="0.1"
                          {...register('temperature_max', { valueAsNumber: true })}
                          placeholder="2"
                        />
                      </div>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Enter temperature range specified in client&apos;s transport instructions or product technical documentation (e.g., frozen: -18°C, chilled: +2 to +4°C).
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Financial Information */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Euro className="h-5 w-5" />
                  Financial Information
                </CardTitle>
                <CardDescription>Freight costs and cash on delivery</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Description: Explain COD to drivers - amount to collect at delivery */}
                <div className="space-y-4">
                  <h4 className="text-sm font-medium">Cash on Delivery (COD)</h4>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="cash_on_delivery_amount">COD Amount</Label>
                      <Input
                        id="cash_on_delivery_amount"
                        type="number"
                        step="1"
                        {...register('cash_on_delivery_amount')}
                        placeholder="5000.00"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="cash_on_delivery_currency">Currency</Label>
                      <Input
                        id="cash_on_delivery_currency"
                        {...register('cash_on_delivery_currency')}
                        placeholder="EUR"
                        maxLength={3}
                      />
                    </div>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Amount the driver must collect from consignee at delivery. Only fill if client requires payment on delivery. Ensure you have proper payment receipt documentation.
                  </p>
                </div>

                <Separator />

                <div className="space-y-4">
                  <h4 className="text-sm font-medium">Freight Charges</h4>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="freight_total_amount">Total Amount</Label>
                      <Input
                        id="freight_total_amount"
                        type="number"
                        step="0.01"
                        {...register('freight_total_amount', { valueAsNumber: true })}
                        placeholder="1500.00"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="freight_currency">Currency</Label>
                      <Input
                        id="freight_currency"
                        {...register('freight_currency')}
                        placeholder="EUR"
                        maxLength={3}
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="freight_terms">Terms</Label>
                      <Input
                        id="freight_terms"
                        {...register('freight_terms')}
                        placeholder="Prepaid, Collect..."
                      />
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Pallets Management */}
            <Card>
              <CardHeader>
                <CardTitle>Pallets Exchange</CardTitle>
                <CardDescription>Track pallet quantities and exchanges</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="pallets_80_120">80x120 cm</Label>
                    <Input
                      id="pallets_80_120"
                      type="number"
                      min="0"
                      {...register('pallets_80_120', { valueAsNumber: true })}
                      placeholder="0"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="pallets_100_120">100x120 cm</Label>
                    <Input
                      id="pallets_100_120"
                      type="number"
                      min="0"
                      {...register('pallets_100_120', { valueAsNumber: true })}
                      placeholder="0"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="pallets_europe">Euro Pallets</Label>
                    <Input
                      id="pallets_europe"
                      type="number"
                      min="0"
                      {...register('pallets_europe', { valueAsNumber: true })}
                      placeholder="0"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="pallets_others">Others</Label>
                    <Input
                      id="pallets_others"
                      type="number"
                      min="0"
                      {...register('pallets_others', { valueAsNumber: true })}
                      placeholder="0"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="pallets_bacs">Bacs</Label>
                    <Input
                      id="pallets_bacs"
                      type="number"
                      min="0"
                      {...register('pallets_bacs', { valueAsNumber: true })}
                      placeholder="0"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="pallets_rolls">Rolls</Label>
                    <Input
                      id="pallets_rolls"
                      type="number"
                      min="0"
                      {...register('pallets_rolls', { valueAsNumber: true })}
                      placeholder="0"
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="pallets_origin">Origin/Ownership</Label>
                  <Input
                    id="pallets_origin"
                    {...register('pallets_origin')}
                    placeholder="e.g., CHEP, LPR, propriétaire"
                  />
                </div>
              </CardContent>
            </Card>

            {/* Instructions & Documents */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="h-5 w-5" />
                  Instructions & Documents
                </CardTitle>
                <CardDescription>Special instructions and attached documents</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="instructions">Special Instructions</Label>
                  <Textarea
                    id="instructions"
                    {...register('instructions')}
                    placeholder="Special handling requirements, delivery instructions, etc."
                    rows={3}
                  />
                </div>

                {isInternational && (
                  <div className="space-y-2">
                    <Label htmlFor="customs_instructions">Customs Instructions</Label>
                    <Textarea
                      id="customs_instructions"
                      {...register('customs_instructions')}
                      placeholder="Customs-related information for international transport"
                      rows={3}
                    />
                  </div>
                )}

                {/* Description: Help drivers understand what documents to list */}
                <div className="space-y-2">
                  <Label htmlFor="attached_documents">Attached Documents</Label>
                  <Input
                    id="attached_documents"
                    {...register('attached_documents')}
                    placeholder="e.g., BL, FDS, certificate, invoice"
                  />
                  <p className="text-xs text-muted-foreground">
                    List accompanying documents: bill of lading (BL), safety data sheet (FDS), quality certificates, commercial invoice, customs docs, etc.
                  </p>
                </div>

                {/* Description: Help drivers understand what services to note */}
                <div className="space-y-2">
                  <Label htmlFor="loading_extra_services">Loading Extra Services</Label>
                  <Input
                    id="loading_extra_services"
                    {...register('loading_extra_services')}
                    placeholder="e.g., tail-lift, crane, special equipment"
                  />
                  <p className="text-xs text-muted-foreground">
                    Special services needed at pickup: tail-lift, forklift, crane, film wrapping, strapping, installation, etc.
                  </p>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="delivery_extra_services">Delivery Extra Services</Label>
                  <Input
                    id="delivery_extra_services"
                    {...register('delivery_extra_services')}
                    placeholder="e.g., tail-lift, crane, special equipment"
                  />
                  <p className="text-xs text-muted-foreground">
                    Special services needed at delivery: tail-lift, forklift, crane, installation, floor placement, etc.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* ====================================================================
            STEP 3 - VEHICLE & SUMMARY
            Vehicle selection and read-only summary before submission
            ==================================================================== */}
        {currentStep === 2 && (
          <div className="space-y-6">
            {/* Vehicle Selection */}
            <Card>
              <CardHeader>
                <CardTitle>Vehicle Selection</CardTitle>
                <CardDescription>Select the vehicle for this transport</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {loadingVehicles ? (
                  <div className="text-sm text-muted-foreground">Loading vehicles...</div>
                ) : vehicles.length === 0 ? (
                  <div className="rounded-md bg-yellow-50 border border-yellow-200 p-4">
                    <p className="text-sm text-yellow-800 font-medium">No vehicles found</p>
                    <p className="text-sm text-yellow-700 mt-1">
                      Please add a vehicle to your fleet before creating a CMR.
                    </p>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      className="mt-3"
                      onClick={() => router.push('/profile?tab=vehicles')}
                    >
                      Add Vehicle
                    </Button>
                  </div>
                ) : (
                  <div className="space-y-2">
                    <Label htmlFor="vehicle_id">Vehicle *</Label>
                    <Controller
                      name="vehicle_id"
                      control={control}
                      render={({ field }) => (
                        <Select onValueChange={field.onChange} value={field.value}>
                          <SelectTrigger className="w-full">
                            <SelectValue placeholder="Select a vehicle" />
                          </SelectTrigger>
                          <SelectContent>
                            {vehicles.map((vehicle) => (
                              <SelectItem key={vehicle.id} value={vehicle.id}>
                                {vehicle.plate} {vehicle.type ? `(${vehicle.type})` : ''}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      )}
                    />
                    {errors.vehicle_id && (
                      <p className="text-sm text-destructive">{errors.vehicle_id.message}</p>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Summary */}
            <Card>
              <CardHeader>
                <CardTitle>Summary</CardTitle>
                <CardDescription>Review your CMR before creating</CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Parties */}
                <div>
                  <h4 className="text-sm font-semibold mb-3">Parties</h4>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                    <div>
                      <p className="font-medium text-muted-foreground">Shipper</p>
                      <p className="font-medium">{formValues.shipper_name || '—'}</p>
                      <p className="text-muted-foreground text-xs">
                        {formValues.shipper_address || '—'}
                      </p>
                    </div>
                    <div>
                      <p className="font-medium text-muted-foreground">Consignee</p>
                      <p className="font-medium">{formValues.consignee_name || '—'}</p>
                      <p className="text-muted-foreground text-xs">
                        {formValues.consignee_address || '—'}
                      </p>
                    </div>
                  </div>
                </div>

                <Separator />

                {/* Goods */}
                <div>
                  <h4 className="text-sm font-semibold mb-3">Goods</h4>
                  <div className="text-sm space-y-2">
                    <p>
                      <span className="font-medium">Description:</span>{' '}
                      {formValues.goods_description || '—'}
                    </p>
                    <p>
                      <span className="font-medium">Quantity:</span> {formValues.packages_count || 0}{' '}
                      packages • {formValues.weight_kg || 0} kg
                    </p>
                    {formValues.packaging_type && (
                      <p>
                        <span className="font-medium">Packaging:</span> {formValues.packaging_type}
                      </p>
                    )}
                  </div>
                </div>

                <Separator />

                {/* Route */}
                <div>
                  <h4 className="text-sm font-semibold mb-3">Route</h4>
                  <div className="text-sm space-y-2">
                    <p>
                      <span className="font-medium">Loading:</span>{' '}
                      {formValues.loading_place || '—'}
                    </p>
                    <p>
                      <span className="font-medium">Delivery:</span>{' '}
                      {formValues.delivery_place || '—'}
                    </p>
                    <p>
                      <span className="font-medium">Date:</span>{' '}
                      {formValues.loading_date
                        ? format(new Date(formValues.loading_date), 'PPP')
                        : '—'}
                    </p>
                  </div>
                </div>

                {/* Conditional sections */}
                {(formValues.is_dangerous_goods ||
                  formValues.is_controlled_temperature ||
                  formValues.is_international) && (
                  <>
                    <Separator />
                    <div>
                      <h4 className="text-sm font-semibold mb-3">Special Conditions</h4>
                      <div className="flex flex-wrap gap-2">
                        {formValues.is_international && (
                          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                            International
                          </span>
                        )}
                        {formValues.is_dangerous_goods && (
                          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-orange-100 text-orange-800">
                            Dangerous Goods (ADR)
                          </span>
                        )}
                        {formValues.is_controlled_temperature && (
                          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                            Temperature Controlled
                          </span>
                        )}
                      </div>
                    </div>
                  </>
                )}
              </CardContent>
            </Card>
          </div>
        )}

        {/* Navigation Buttons */}
       <div className="flex gap-4">
          <Button
            type="button"
            variant="outline"
            onClick={currentStep === 0 ? () => router.back() : handleBack}
            disabled={loading}
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            {currentStep === 0 ? 'Cancel' : 'Back'}
          </Button>

          {currentStep < STEPS.length - 1 ? (
            // 👉 NEXT ne fait que changer de step, jamais de submit
            <Button
              type="button"
              onClick={handleNext}
              className="flex-1"
            >
              Next
              <ArrowRight className="h-4 w-4 ml-2" />
            </Button>
          ) : (
            // 👉 SEUL CE BOUTON PEUT SOUMETTRE LE FORMULAIRE
            <Button
              type="button"
              onClick={handleSubmit(onSubmit)}
              disabled={isSubmitting || loading || vehicles.length === 0}
              className="flex-1"
            >
              {isSubmitting || loading ? (
                'Creating...'
              ) : (
                <>
                  <Check className="h-4 w-4 mr-2" />
                  Create CMR
                </>
              )}
            </Button>
          )}
        </div>
      </form>
    </div>
  );
}
